//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditOnline.CRServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRServiceProxy.ICRService")]
    public interface ICRService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/IsAlive", ReplyAction="http://tempuri.org/ICRService/IsAliveResponse")]
        bool IsAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/GetDicModel", ReplyAction="http://tempuri.org/ICRService/GetDicModelResponse")]
        System.Collections.Generic.List<CRModel.Models.DicModel> GetDicModel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/CheckUser", ReplyAction="http://tempuri.org/ICRService/CheckUserResponse")]
        bool CheckUser(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/GetSearchReportData", ReplyAction="http://tempuri.org/ICRService/GetSearchReportDataResponse")]
        System.Collections.Generic.List<CRModel.Models.SearchResultModel> GetSearchReportData(out int totalCount, int pageNumber, int pageSize, System.Collections.Generic.Dictionary<string, string> searchParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/NewOrder", ReplyAction="http://tempuri.org/ICRService/NewOrderResponse")]
        bool NewOrder(CRModel.Models.OrderModel models, CRModel.Models.ContractModel contractmodel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/NewMultiOrder", ReplyAction="http://tempuri.org/ICRService/NewMultiOrderResponse")]
        bool NewMultiOrder(System.Collections.Generic.List<CRModel.Models.OrderModel> multimodels, CRModel.Models.ContractModel contractmodel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/GetContractDetails", ReplyAction="http://tempuri.org/ICRService/GetContractDetailsResponse")]
        CRModel.Models.ContractModel GetContractDetails(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/GetEnterpriseInfo", ReplyAction="http://tempuri.org/ICRService/GetEnterpriseInfoResponse")]
        CRModel.Models.EnterpriseInfoModel GetEnterpriseInfo(string creditno, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/GetReportDetais", ReplyAction="http://tempuri.org/ICRService/GetReportDetaisResponse")]
        System.Collections.Generic.List<CRModel.Models.ReportDetailsModel> GetReportDetais(out int totalCount, int pageNumber, int pageSize, System.Collections.Generic.Dictionary<string, string> searchParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/GetEmailErrorDetais", ReplyAction="http://tempuri.org/ICRService/GetEmailErrorDetaisResponse")]
        System.Collections.Generic.List<CRModel.Models.EmailErrorDetailsModel> GetEmailErrorDetais(out int totalCount, int pageNumber, int pageSize, System.Collections.Generic.Dictionary<string, string> searchParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/GetContractNation", ReplyAction="http://tempuri.org/ICRService/GetContractNationResponse")]
        System.Collections.Generic.Dictionary<string, string> GetContractNation(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/EditPassword", ReplyAction="http://tempuri.org/ICRService/EditPasswordResponse")]
        bool EditPassword(string username, string oldpass, string newpass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/GetDataandFee", ReplyAction="http://tempuri.org/ICRService/GetDataandFeeResponse")]
        System.Collections.Generic.List<string> GetDataandFee(string username, string nationcode, string expresstype, string reporttype, string selectedlang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/GetContractDetailsByEmail", ReplyAction="http://tempuri.org/ICRService/GetContractDetailsByEmailResponse")]
        CRModel.Models.ContractModel GetContractDetailsByEmail(string emailaddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/GetContractDetailsByOrg", ReplyAction="http://tempuri.org/ICRService/GetContractDetailsByOrgResponse")]
        CRModel.Models.ContractModel GetContractDetailsByOrg(string resultOwnership);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/GetUnreadMsgUids", ReplyAction="http://tempuri.org/ICRService/GetUnreadMsgUidsResponse")]
        System.Collections.Generic.Dictionary<int, string> GetUnreadMsgUids(System.Collections.Generic.Dictionary<int, string> alluids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/SaveEmail", ReplyAction="http://tempuri.org/ICRService/SaveEmailResponse")]
        bool SaveEmail(CRModel.Models.EmailOrderModel model, bool isEdit, string customerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/CheckNeedSendEmail", ReplyAction="http://tempuri.org/ICRService/CheckNeedSendEmailResponse")]
        bool CheckNeedSendEmail(string profileno, string context);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/CheckUrgent", ReplyAction="http://tempuri.org/ICRService/CheckUrgentResponse")]
        System.Collections.Generic.Dictionary<string, bool> CheckUrgent(string username, string nationcode, string reporttype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/GetNationDetails", ReplyAction="http://tempuri.org/ICRService/GetNationDetailsResponse")]
        CRModel.Models.NationModel GetNationDetails(string shorten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/SynctoCPWP", ReplyAction="http://tempuri.org/ICRService/SynctoCPWPResponse")]
        void SynctoCPWP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/GetDisplayName", ReplyAction="http://tempuri.org/ICRService/GetDisplayNameResponse")]
        string GetDisplayName(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/CheckCustomerReportNO", ReplyAction="http://tempuri.org/ICRService/CheckCustomerReportNOResponse")]
        string CheckCustomerReportNO(string cusreportno, string currentuser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/GetEmailDetails", ReplyAction="http://tempuri.org/ICRService/GetEmailDetailsResponse")]
        string GetEmailDetails(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/GetSyncCPWPErrorDetais", ReplyAction="http://tempuri.org/ICRService/GetSyncCPWPErrorDetaisResponse")]
        System.Collections.Generic.List<CRModel.Models.EmailErrorDetailsModel> GetSyncCPWPErrorDetais(out int totalCount, int pageNumber, int pageSize, System.Collections.Generic.Dictionary<string, string> searchParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/GetCPWPError", ReplyAction="http://tempuri.org/ICRService/GetCPWPErrorResponse")]
        string GetCPWPError(string orderno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/UpdateReportOrderStatus", ReplyAction="http://tempuri.org/ICRService/UpdateReportOrderStatusResponse")]
        CRModel.Models.ReturnObject UpdateReportOrderStatus(string orderNO, string orderStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRService/CompleteReportOrder", ReplyAction="http://tempuri.org/ICRService/CompleteReportOrderResponse")]
        CRModel.Models.ReturnObject CompleteReportOrder(System.Collections.Generic.List<CRModel.Models.ReportInfo> infos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRServiceChannel : CreditOnline.CRServiceProxy.ICRService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRServiceClient : System.ServiceModel.ClientBase<CreditOnline.CRServiceProxy.ICRService>, CreditOnline.CRServiceProxy.ICRService {
        
        public CRServiceClient() {
        }
        
        public CRServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsAlive() {
            return base.Channel.IsAlive();
        }
        
        public System.Collections.Generic.List<CRModel.Models.DicModel> GetDicModel() {
            return base.Channel.GetDicModel();
        }
        
        public bool CheckUser(string name, string password) {
            return base.Channel.CheckUser(name, password);
        }
        
        public System.Collections.Generic.List<CRModel.Models.SearchResultModel> GetSearchReportData(out int totalCount, int pageNumber, int pageSize, System.Collections.Generic.Dictionary<string, string> searchParams) {
            return base.Channel.GetSearchReportData(out totalCount, pageNumber, pageSize, searchParams);
        }
        
        public bool NewOrder(CRModel.Models.OrderModel models, CRModel.Models.ContractModel contractmodel) {
            return base.Channel.NewOrder(models, contractmodel);
        }
        
        public bool NewMultiOrder(System.Collections.Generic.List<CRModel.Models.OrderModel> multimodels, CRModel.Models.ContractModel contractmodel) {
            return base.Channel.NewMultiOrder(multimodels, contractmodel);
        }
        
        public CRModel.Models.ContractModel GetContractDetails(string username) {
            return base.Channel.GetContractDetails(username);
        }
        
        public CRModel.Models.EnterpriseInfoModel GetEnterpriseInfo(string creditno, string username) {
            return base.Channel.GetEnterpriseInfo(creditno, username);
        }
        
        public System.Collections.Generic.List<CRModel.Models.ReportDetailsModel> GetReportDetais(out int totalCount, int pageNumber, int pageSize, System.Collections.Generic.Dictionary<string, string> searchParams) {
            return base.Channel.GetReportDetais(out totalCount, pageNumber, pageSize, searchParams);
        }
        
        public System.Collections.Generic.List<CRModel.Models.EmailErrorDetailsModel> GetEmailErrorDetais(out int totalCount, int pageNumber, int pageSize, System.Collections.Generic.Dictionary<string, string> searchParams) {
            return base.Channel.GetEmailErrorDetais(out totalCount, pageNumber, pageSize, searchParams);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetContractNation(string username) {
            return base.Channel.GetContractNation(username);
        }
        
        public bool EditPassword(string username, string oldpass, string newpass) {
            return base.Channel.EditPassword(username, oldpass, newpass);
        }
        
        public System.Collections.Generic.List<string> GetDataandFee(string username, string nationcode, string expresstype, string reporttype, string selectedlang) {
            return base.Channel.GetDataandFee(username, nationcode, expresstype, reporttype, selectedlang);
        }
        
        public CRModel.Models.ContractModel GetContractDetailsByEmail(string emailaddress) {
            return base.Channel.GetContractDetailsByEmail(emailaddress);
        }
        
        public CRModel.Models.ContractModel GetContractDetailsByOrg(string resultOwnership) {
            return base.Channel.GetContractDetailsByOrg(resultOwnership);
        }
        
        public System.Collections.Generic.Dictionary<int, string> GetUnreadMsgUids(System.Collections.Generic.Dictionary<int, string> alluids) {
            return base.Channel.GetUnreadMsgUids(alluids);
        }
        
        public bool SaveEmail(CRModel.Models.EmailOrderModel model, bool isEdit, string customerid) {
            return base.Channel.SaveEmail(model, isEdit, customerid);
        }
        
        public bool CheckNeedSendEmail(string profileno, string context) {
            return base.Channel.CheckNeedSendEmail(profileno, context);
        }
        
        public System.Collections.Generic.Dictionary<string, bool> CheckUrgent(string username, string nationcode, string reporttype) {
            return base.Channel.CheckUrgent(username, nationcode, reporttype);
        }
        
        public CRModel.Models.NationModel GetNationDetails(string shorten) {
            return base.Channel.GetNationDetails(shorten);
        }
        
        public void SynctoCPWP() {
            base.Channel.SynctoCPWP();
        }
        
        public string GetDisplayName(string userid) {
            return base.Channel.GetDisplayName(userid);
        }
        
        public string CheckCustomerReportNO(string cusreportno, string currentuser) {
            return base.Channel.CheckCustomerReportNO(cusreportno, currentuser);
        }
        
        public string GetEmailDetails(string uid) {
            return base.Channel.GetEmailDetails(uid);
        }
        
        public System.Collections.Generic.List<CRModel.Models.EmailErrorDetailsModel> GetSyncCPWPErrorDetais(out int totalCount, int pageNumber, int pageSize, System.Collections.Generic.Dictionary<string, string> searchParams) {
            return base.Channel.GetSyncCPWPErrorDetais(out totalCount, pageNumber, pageSize, searchParams);
        }
        
        public string GetCPWPError(string orderno) {
            return base.Channel.GetCPWPError(orderno);
        }
        
        public CRModel.Models.ReturnObject UpdateReportOrderStatus(string orderNO, string orderStatus) {
            return base.Channel.UpdateReportOrderStatus(orderNO, orderStatus);
        }
        
        public CRModel.Models.ReturnObject CompleteReportOrder(System.Collections.Generic.List<CRModel.Models.ReportInfo> infos) {
            return base.Channel.CompleteReportOrder(infos);
        }
    }
}
